@startuml
skinparam linetype ortho

database FakeMessages #line.dashed;
database TextMessageBase
database SquishMessageBase

component makesqbase
component extractsqbase
component fakemsg.py


FakeMessages <-[dashed]r- fakemsg.py
FakeMessages -u-> makesqbase
makesqbase -> SquishMessageBase
SquishMessageBase -> extractsqbase
TextMessageBase <-u- extractsqbase

@enduml